apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "python-app=ptibor84/python-app:latest"
    argocd-image-updater.argoproj.io/python-app.helm.image-name: "python-app.deployment.image.repository"
    argocd-image-updater.argoproj.io/python-app.update-strategy: "latest"
    argocd-image-updater.argoproj.io/pull-policy: Always
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/odeeka/python-app.git
    targetRevision: HEAD
    path: charts/python-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: python-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
