name: ci

on:
  workflow_dispatch:

  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA

      - name: Set outputs
        id: vars
        run: echo "sha_short=${GITHUB_SHA::5}" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ptibor84/python-app:${{ steps.vars.outputs.sha_short }}
            ptibor84/python-app:latest
